name: aws_s3_polar
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  get: ^4.6.6
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  cloudinary_flutter: ^1.3.0
  cloudinary: ^1.2.0
  get_storage: ^2.1.1
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
